force-app/main/default/objects/Lead/fields/Direct_Phone__c.field-meta.xml
<CustomField>
    <fullName>Direct_Phone__c</fullName>
    <label>Direct Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Duplicate_Check__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Original_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Original_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Preferred_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Name__c</fullName>
    <label>Preferred Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadFilters.cls
public with sharing class LeadFilters {

    public static Select.Filter hasEmailOptOut() {
        return Select.Field.isEqual(Lead.HasOptedOutOfEmail, true).andX(
            Select.Field.notEqual(Lead.Email, null)
        );
    }

    public static Select.Filter hasDuplicateCheckOn() {
        return Select.Field.isEqual(Lead.Duplicate_Check__c, true);
    }

    public static Select.Filter hasPhoneNumber() {
        return Select.Field.notEqual(Lead.Phone, null).orX(
            Select.Field.notEqual(Lead.Direct_Phone__c, null).orX(
            Select.Field.notEqual(Lead.MobilePhone, null).orX(
            Select.Field.notEqual(Lead.Fax, null)
        )));        
    }

    public static Select.Filter hasNoPreferredName() {
        return Select.Field.isEqual(Lead.Preferred_Name__c, null);
    }
    
    public static Select.Filter hasOriginalCampaign() {
        return Select.Field.notEqual(Lead.Original_Campaign__c, null);
    }

    public static Select.Filter changedEmailOptOut() {
        return Select.Field.hasChanged(Lead.HasOptedOutOfEmail).andX(
            Select.Field.notEqual(Lead.Email, null)
        );
    }
    
    public static Select.Filter changedOriginalCampaign() {
        return Select.Field.hasChanged(Lead.Original_Campaign__c);
    }
    
    public static Select.Filter isConverted() {
    	return Select.Field.isEqual(Lead.IsConverted, true).andX(
    		Select.Field.hasChanged(Lead.IsConverted)
    	);
    }

}